### ISSUE TITLE
2.

### ISSUE THREAD

**Issue by inelukipg** [flancer32/mage2_fix_pr9621#1] opened 2017-09-12 14:15 UTC
Hi,
I'm using 0.1.0 (I think)

Could I run composer update to fetch the new 0.2.0 version?

**Comment by flancer64** [comment] 2017-09-12 16:59
Hi,

I suppose you can try to do it. 

You can see version of the each composer's module in `composer.lock` file under your project's root.

If composer's update will failed you can manually replace `.vendor/flancer32/mage2_fix_pr9621/Fw/DB/Query/BatchIterator.php` file with new one (https://raw.githubusercontent.com/flancer32/mage2_fix_pr9621/0.2.0/Fw/DB/Query/BatchIterator.php)

I hope this helps you.

**Comment by flancer64** [comment] 2017-09-12 20:34
U-ups... I found a bugs in my fix. Magento does not use \Magento\Framework\DB\Query\BatchIterator for Catalog Product indexing in 2.1.8. Class \Magento\Framework\DB\Query\BatchRangeIterator is used instead. I have no fixes for this class yet.

**Comment by flancer64** [comment] 2017-09-13 05:14
Hi,

I investigated 2.1.8 indexing process and found that `\Magento\Framework\DB\Query\BatchRangeIterator` is used in 2.1.8 instead of `\Magento\Framework\DB\Query\BatchIterator` in 2.1.7. I cannot reproduce bug I have fixed with `BatchRangeIterator` in 2.1.8. So, you should not use my module in 2.1.8.

**Closed as completed by flancer64** 2017-09-13 05:14 UTC
